// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/discord-player/Current.tsx": () => import("../components/mockups/discord-player/Current.tsx"),
  "./components/mockups/discord-player/New.tsx": () => import("../components/mockups/discord-player/New.tsx")
};
