'use strict';
/**
 * likes.js — NeDB embedded database
 * Pure JavaScript, no native binaries, no WASM, no GLIBC dependency.
 * Works on Railway, Replit, Docker, any Node.js >= 14 environment.
 *
 * Schema per document:
 *   { userId, uri, title, author, duration, likedAt }
 *   _id auto-generated by NeDB
 */

const path      = require('path');
const fs        = require('fs');
const Datastore = require('@seald-io/nedb');

// ── Ensure settings/ dir exists before NeDB tries to create the file ─────────
const SETTINGS_DIR = path.join(process.cwd(), 'settings');
try { if (!fs.existsSync(SETTINGS_DIR)) fs.mkdirSync(SETTINGS_DIR, { recursive: true }); }
catch (e) { console.error('[Likes] Could not create settings dir:', e.message); }

const DB_PATH = path.join(SETTINGS_DIR, 'likes.nedb');

// ── Open datastore ─────────────────────────────────────────────────────────────
const db = new Datastore({
    filename:  DB_PATH,
    autoload:  true,
    onload:    (err) => {
        if (err) console.error('[Likes] DB load error:', err.message);
        else console.log('[Likes] DB loaded:', DB_PATH);
    },
    // Compact the file every 24h to reclaim space from deleted docs
    corruptAlertThreshold: 0.3,
});

// Compact every 24 h
db.setAutocompactionInterval(24 * 60 * 60 * 1000);

// ── Indexes for fast lookups ───────────────────────────────────────────────────
db.ensureIndex({ fieldName: 'userId' }, (err) => {
    if (err) console.error('[Likes] ensureIndex userId:', err.message);
});
db.ensureIndex({ fieldName: 'uri' }, (err) => {
    if (err) console.error('[Likes] ensureIndex uri:', err.message);
});
// Compound-style: NeDB doesn't support compound indexes, but
// userId index + in-query uri filter is fast enough for this use-case.

// ── Per-user write lock (prevent race conditions on toggle) ──────────────────
const locks = new Map();

function withUserLock(userId, task) {
    const key      = String(userId || 'global');
    const previous = locks.get(key) || Promise.resolve();
    const next     = previous
        .catch(() => {})
        .then(task)
        .finally(() => { if (locks.get(key) === next) locks.delete(key); });
    locks.set(key, next);
    return next;
}

// ── Derive a stable key from a track object ───────────────────────────────────
function trackKey(track) {
    const info = track?.info || track || {};
    return info.uri
        || info.identifier
        || [info.sourceName, info.author, info.title, info.length].filter(Boolean).join(':')
        || null;
}

// ── Promisify helpers ─────────────────────────────────────────────────────────
function dbFindOne(query) {
    return new Promise((resolve, reject) =>
        db.findOne(query, (err, doc) => err ? reject(err) : resolve(doc))
    );
}

function dbFind(query, sort, skip, limit) {
    return new Promise((resolve, reject) => {
        let cursor = db.find(query).sort(sort);
        if (skip  != null) cursor = cursor.skip(skip);
        if (limit != null) cursor = cursor.limit(limit);
        cursor.exec((err, docs) => err ? reject(err) : resolve(docs || []));
    });
}

function dbCount(query) {
    return new Promise((resolve, reject) =>
        db.count(query, (err, n) => err ? reject(err) : resolve(n || 0))
    );
}

function dbInsert(doc) {
    return new Promise((resolve, reject) =>
        db.insert(doc, (err, newDoc) => err ? reject(err) : resolve(newDoc))
    );
}

function dbRemove(query) {
    return new Promise((resolve, reject) =>
        db.remove(query, {}, (err, n) => err ? reject(err) : resolve(n))
    );
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Toggle like for a track.
 * @returns {Promise<{ liked: boolean }>}
 */
function toggle(userId, track) {
    return withUserLock(userId, async () => {
        const info   = track?.info || {};
        const uri    = trackKey(track);
        if (!userId || !uri) throw new Error('[Likes] toggle: missing userId or uri');

        const existing = await dbFindOne({ userId, uri }).catch((err) => {
            console.error('[Likes] toggle findOne error:', err.message);
            throw err;
        });

        if (existing) {
            await dbRemove({ userId, uri }).catch((err) => {
                console.error('[Likes] toggle remove error:', err.message);
                throw err;
            });
            return { liked: false };
        }

        await dbInsert({
            userId,
            uri,
            title:    info.title  || 'Unknown track',
            author:   info.author || '',
            duration: Number(info.length || 0),
            likedAt:  Date.now(),
        }).catch((err) => {
            console.error('[Likes] toggle insert error:', err.message);
            throw err;
        });

        return { liked: true };
    });
}

/**
 * Check if a track is liked by the user.
 * @returns {Promise<boolean>}
 */
async function isLiked(userId, uriOrTrack) {
    try {
        const uri = typeof uriOrTrack === 'string' ? uriOrTrack : trackKey(uriOrTrack);
        if (!userId || !uri) return false;
        const doc = await dbFindOne({ userId, uri });
        return !!doc;
    } catch (err) {
        console.error('[Likes] isLiked error:', err.message);
        return false;   // fallback: treat as not liked
    }
}

/**
 * Get paginated likes for a user.
 * @returns {Promise<{ rows: Array, total: number }>}
 */
async function getLikes(userId, { offset = 0, limit = 10 } = {}) {
    try {
        const [total, rows] = await Promise.all([
            dbCount({ userId }),
            dbFind({ userId }, { likedAt: -1 }, offset, limit),
        ]);
        return { rows, total };
    } catch (err) {
        console.error('[Likes] getLikes error:', err.message);
        return { rows: [], total: 0 };  // fallback: empty result
    }
}

/**
 * Get all likes for a user (for queueing).
 * @returns {Promise<Array>}
 */
async function getAllLikes(userId) {
    try {
        return await dbFind({ userId }, { likedAt: -1 }, null, null);
    } catch (err) {
        console.error('[Likes] getAllLikes error:', err.message);
        return [];  // fallback: empty list
    }
}

module.exports = { toggle, isLiked, getLikes, getAllLikes, trackKey };
